# Generated by Django 5.0.6 on 2024-05-21 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GamePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('text', models.TextField()),
                ('CategoryCheck', models.CharField(blank=True, choices=[('Танки', 'Cat 1'), ('Хилы', 'Cat 2'), ('ДД', 'Cat 3'), ('Торговцы', 'Cat 4'), ('Гилдмастеры', 'Cat 5'), ('Квестгиверы', 'Cat 6'), ('Кузнецы', 'Cat 7'), ('Кожевники', 'Cat 8'), ('Зельевары', 'Cat 9'), ('Мастера заклинаний', 'Cat 10')], max_length=100)),
                ('link_GameUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RPG_FUNCTIONS.gameuser')),
            ],
        ),
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_otm_Post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RPG_FUNCTIONS.gamepost')),
            ],
        ),
    ]
